CREATE DATABASE mmpi;
USE mmpi;


CREATE TABLE ACCESO (
    ID_ACCESO INT PRIMARY KEY AUTO_INCREMENT,
    USUARIO VARCHAR(50) NOT NULL,
    CONTRASENA VARCHAR(50) NOT NULL
);


CREATE TABLE FISIOTERAPEUTA (
    DNI_FISIO VARCHAR(9) PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(50) NOT NULL,
    DOMICILIO VARCHAR(50),
    EMAIL VARCHAR(50),
    TELEFONO INT(9),
    ID_ACCESO INT,
    
    CONSTRAINT FK_FISIOTERAPEUTA_ACCESO 
        FOREIGN KEY (ID_ACCESO) 
        REFERENCES ACCESO(ID_ACCESO)
        ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE PACIENTE (
    DNI_PACIENTE VARCHAR(9) PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(50) NOT NULL,
    DOMICILIO VARCHAR(50),
    EMAIL VARCHAR(50),
    TELEFONO INT(9),
    DNI_FISIO VARCHAR(9),
    
    CONSTRAINT FK_PACIENTE_FISIOTERAPEUTA 
        FOREIGN KEY (DNI_FISIO) 
        REFERENCES FISIOTERAPEUTA(DNI_FISIO)
        ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE DISPOSITIVO (
    ID_DISPOSITIVO INT PRIMARY KEY AUTO_INCREMENT
);


CREATE TABLE SESION (
    ID_SESION VARCHAR(5) PRIMARY KEY,
    ACELERACIONES_BRUSCAS INT,
    COLISIONES INT,
    ESTABILIDAD INT,
    NIVEL INT,
    PARADAS_BRUSCAS INT,
    SCORE INT,
    TIEMPO_MOVIMIENTO INT,
    TIEMPO_SESION TIMESTAMP,
    DNI_FISIO VARCHAR(9), 
    DNI_PACIENTE VARCHAR(9), 
    ID_DISPOSITIVO INT,
    
    CONSTRAINT FK_SESION_FISIOTERAPEUTA 
        FOREIGN KEY (DNI_FISIO) 
        REFERENCES FISIOTERAPEUTA(DNI_FISIO)
        ON UPDATE CASCADE ON DELETE CASCADE,
    
    CONSTRAINT FK_SESION_PACIENTE 
        FOREIGN KEY (DNI_PACIENTE) 
        REFERENCES PACIENTE(DNI_PACIENTE)
        ON UPDATE CASCADE ON DELETE CASCADE,
    
    CONSTRAINT FK_SESION_DISPOSITIVO 
        FOREIGN KEY (ID_DISPOSITIVO) 
        REFERENCES DISPOSITIVO(ID_DISPOSITIVO)
        ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE EVENTO (
    ID_EVENTO INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION VARCHAR(50),
    TIPO_EVENTO VARCHAR(50),
    ID_SESION VARCHAR(5),
    
    CONSTRAINT FK_EVENTO_SESION 
        FOREIGN KEY (ID_SESION) 
        REFERENCES SESION(ID_SESION)
        ON UPDATE CASCADE ON DELETE CASCADE
);