CREATE DATABASE mmpi;
USE mmpi;

CREATE TABLE ACCESO (
    ID_ACCESO INT PRIMARY KEY AUTO_INCREMENT,
    USUARIO VARCHAR(50) NOT NULL,
    CONTRASENA VARCHAR(100) NOT NULL
);


CREATE TABLE FISIOTERAPEUTA (
    ID_NUMERO_COLEGIADO INT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    DOMICILIO VARCHAR(150),
    EMAIL VARCHAR(100),
    TELEFONO VARCHAR(20),
    ID_ACCESO INT,
   
   CONSTRAINT FK_FISIO_ACCESO 
        FOREIGN KEY (ID_ACCESO) 
        REFERENCES ACCESO(ID_ACCESO)
        ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE PACIENTES (
    ID_DNI_PAC VARCHAR(20) PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    FECHA_NACIMIENTO DATE,
    EMAIL VARCHAR(100),
    TELEFONO VARCHAR(20)
);


CREATE TABLE DISPOSITIVO (
    ID_NUM_SERIE VARCHAR(50) PRIMARY KEY,
    FECHA_INICIO DATE,
    DURACION INT,
    FECHA_FIN DATE,
    NIVEL VARCHAR(50),
    CATEGORIA VARCHAR(50),
    ID_DNI_PAC_FK VARCHAR(20),
    
    CONSTRAINT FK_DISPOSITIVO_PACIENTE 
        FOREIGN KEY (ID_DNI_PAC_FK) 
        REFERENCES PACIENTES(ID_DNI_PAC)
        ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE SESION (
    ID_SESION INT PRIMARY KEY AUTO_INCREMENT,
    FECHA DATE,
    NOTAS TEXT,
    ID_DNI_PAC_FK VARCHAR(20),
    ID_NUMERO_COLEGIADO_FK INT,
    
    CONSTRAINT FK_SESION_PACIENTE 
        FOREIGN KEY (ID_DNI_PAC_FK) 
        REFERENCES PACIENTES(ID_DNI_PAC)
        ON UPDATE CASCADE ON DELETE CASCADE,
    
    CONSTRAINT FK_SESION_FISIO 
        FOREIGN KEY (ID_NUMERO_COLEGIADO_FK) 
        REFERENCES FISIOTERAPEUTA(ID_NUMERO_COLEGIADO)
        ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE REGISTROS_MOVIMIENTOS (
    ID_MOVIMIENTO INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_EVENTO VARCHAR(100),
    TIMESTAMPT DATETIME,
    ID_SESION INT,
    
    CONSTRAINT FK_REGISTRO_SESION 
        FOREIGN KEY (ID_SESION) 
        REFERENCES SESION(ID_SESION)
        ON UPDATE CASCADE ON DELETE CASCADE
);