DROP DATABASE IF EXISTS mmpi;
CREATE DATABASE mmpi CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE mmpi;

CREATE TABLE ACCESO (
    ID_ACCESO INT PRIMARY KEY AUTO_INCREMENT,
    USUARIO VARCHAR(100) NOT NULL,
    CONTRASENA VARCHAR(100) NOT NULL
);

CREATE TABLE FISIOTERAPEUTA (
    DNI_FISIO VARCHAR(9) PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(50) NOT NULL,
    DOMICILIO VARCHAR(100),
    EMAIL VARCHAR(100),
    TELEFONO INT,
    ID_ACCESO INT,

    CONSTRAINT FK_FISIOTERAPEUTA_ACCESO
        FOREIGN KEY (ID_ACCESO)
        REFERENCES ACCESO(ID_ACCESO)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE PACIENTE (
    DNI_PACIENTE VARCHAR(50) PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(50) NOT NULL,
    DOMICILIO VARCHAR(100),
    EMAIL VARCHAR(100),
    TELEFONO INT,
    EDAD INT,
    LOCALIDAD VARCHAR(100),
    DATOS_COMPLETOS INT DEFAULT 0,
    DNI_FISIO VARCHAR(9),

    CONSTRAINT FK_PACIENTE_FISIOTERAPEUTA
        FOREIGN KEY (DNI_FISIO)
        REFERENCES FISIOTERAPEUTA(DNI_FISIO)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE DISPOSITIVO (
    ID_DISPOSITIVO INT PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE SESION (
    ID_SESION VARCHAR(50) PRIMARY KEY,
    ACELERACIONES_BRUSCAS INT,
    COLISIONES INT,
    ESTABILIDAD INT,
    NIVEL VARCHAR(100),
    PARADAS_BRUSCAS INT,
    SCORE INT,
    TIEMPO_MOVIMIENTO INT,
    TIEMPO_SESION TIMESTAMP NULL,
    DNI_FISIO VARCHAR(9),
    DNI_PACIENTE VARCHAR(50),
    ID_DISPOSITIVO INT,

    CONSTRAINT FK_SESION_FISIOTERAPEUTA
        FOREIGN KEY (DNI_FISIO)
        REFERENCES FISIOTERAPEUTA(DNI_FISIO)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT FK_SESION_PACIENTE
        FOREIGN KEY (DNI_PACIENTE)
        REFERENCES PACIENTE(DNI_PACIENTE)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT FK_SESION_DISPOSITIVO
        FOREIGN KEY (ID_DISPOSITIVO)
        REFERENCES DISPOSITIVO(ID_DISPOSITIVO)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE EVENTO (
    ID_EVENTO INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION VARCHAR(100),
    TIPO_EVENTO VARCHAR(50),
    ID_SESION VARCHAR(50),

    CONSTRAINT FK_EVENTO_SESION
        FOREIGN KEY (ID_SESION)
        REFERENCES SESION(ID_SESION)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE OBSERVACION (
    ID_OBSERVACION INT PRIMARY KEY AUTO_INCREMENT,
    DNI_PACIENTE VARCHAR(50) NOT NULL,
    TIPO_PERIODO VARCHAR(20) NOT NULL,
    FECHA_INICIO DATE NULL,
    FECHA_FIN DATE NULL,
    CLAVE_PERIODO VARCHAR(100) NOT NULL,
    TEXTO TEXT NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT FK_OBSERVACION_PACIENTE
        FOREIGN KEY (DNI_PACIENTE)
        REFERENCES PACIENTE(DNI_PACIENTE)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT UK_OBSERVACION_PERIODO
        UNIQUE (DNI_PACIENTE, TIPO_PERIODO, CLAVE_PERIODO),

    CONSTRAINT CHK_OBSERVACION_TIPO
        CHECK (TIPO_PERIODO IN ('DIA', 'SEMANA', 'GLOBAL'))
);

CREATE INDEX IDX_OBSERVACION_PACIENTE
    ON OBSERVACION (DNI_PACIENTE);

CREATE INDEX IDX_OBSERVACION_PERIODO
    ON OBSERVACION (DNI_PACIENTE, TIPO_PERIODO, CLAVE_PERIODO);

DROP USER IF EXISTS 'appuser'@'%';
CREATE USER 'appuser'@'%' IDENTIFIED BY 'appPass123';
GRANT ALL PRIVILEGES ON mmpi.* TO 'appuser'@'%';
FLUSH PRIVILEGES;